version: "3"
services:
  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: plathanus
      POSTGRES_PASSWORD: plathanus
      POSTGRES_DB: plathanus
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data